# Generated by Django 3.2.13 on 2022-05-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='buy',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
